# ç¿»è¨³å…ˆã®è¨€èª
# lang: ja

# arxivã®å­¦å•é ˜åŸŸã®æŒ‡å®š
subject: cat:cond-mat.*

# æ¤œç´¢ã‚­ãƒ¼ãƒ¯ãƒ¼ãƒ‰
keywords:
        Berry: 1
        graphene: 1
        Hall effect: 1
        heterostructure: 1
        topological : 1
        van der Waals: 1

# é€šçŸ¥ã®é–¾å€¤
score_threshold: 1

# 1å›ã®æœ€å¤§é€šçŸ¥æ•°
max_posts: 8

# ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸ãƒ†ãƒ³ãƒ—ãƒ¬ãƒ¼ãƒˆ
template: |
        <${arxiv_url}|*${title_trans}*>
        ğŸ‘¤ *Authors*: ${authors}
        ğŸ”‘ *Keywords*: ${words}
        âš½ *Score*: ${score}
        ğŸ“ *Abstract*:
        ã€€${summary_trans}
        ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£
