# ç¿»è¨³å…ˆã®è¨€èª
lang: ja

# arxivã®å­¦å•é ˜åŸŸã®æŒ‡å®š
subject: cat:cond-mat.*

# æ¤œç´¢ã‚­ãƒ¼ãƒ¯ãƒ¼ãƒ‰
keywords:
        # Tier 1
        chirality-induced spin selectivity: 3
        spin ice: 3
        variable-range hopping: 3
        # Tier 2
        Berry: 1
        Ettingshausen: 1
        moirÃ©: 1
        multi-valley: 1
        multiferro: 1
        Nernst: 1
        nodal line: 1
        Peltier: 1
        photovoltaic: 1
        pyrochlore: 1
        Seebeck: 1
        shift current: 1
        skyrmion: 1
        thermoelectric: 1
        topological insulator: 1
        valley Hall: 1
        valleytronics: 1
        # Tier 3
        Floquet: 0.5
        magnon: 0.5
        chiral: 0.5
        phonon: 0.5
        bilayer: 0.5
        graphene: 0.5
        anomalous: 0.5
        Hall effect: 0.5
        van der Waals: 0.5
        heterostructure: 0.5
        Dirac: 0.5
        Weyl: 0.5
        semimetal: 0.5

# é€šçŸ¥ã®é–¾å€¤
score_threshold: 1

# 1å›ã®æœ€å¤§é€šçŸ¥æ•°
max_posts: 9

# Front matter template
front_matter: |
        ${num} posts on ${date}
        â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

# ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸ãƒ†ãƒ³ãƒ—ãƒ¬ãƒ¼ãƒˆ
template: |
        <${arxiv_url}|*${title_trans}*>
        ğŸ‘¤ *Authors*: ${authors}
        ğŸ”‘ *Keywords*: ${words} (${score})
        ğŸ“ *Abstract*:
        ã€€${summary_trans}
        â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

# flags: [console, dollar]
