# ç¿»è¨³å…ˆã®è¨€èª
lang: ja

# arxivã®å­¦å•é ˜åŸŸã®æŒ‡å®š
subject: cat:cond-mat.*

# æ¤œç´¢ã‚­ãƒ¼ãƒ¯ãƒ¼ãƒ‰
keywords:
        chirality-induced spin selectivity: 3
        spin ice: 3
        variable-range hopping: 3
        anomalous Hall effect: 1
        Berry: 1
        Floquet: 1
        magnon: 1
        multi-valley: 1
        Nernst effect: 1
        nodal line: 1
        pyrochlore: 1
        Seebeck: 1
        shift current: 1
        skyrmion: 1
        spin Hall effect: 1
        thermoelectric: 1
        topological insulator: 1
        Weyl semimetal: 1
        bilayer graphene: 0.5
        chiral: 0.5
        heterostructure: 0.5
        impurity: 0.5
        phonon: 0.5
        van der Waals: 0.5

# é€šçŸ¥ã®é–¾å€¤
score_threshold: 1

# 1å›ã®æœ€å¤§é€šçŸ¥æ•°
max_posts: 9

# ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸ãƒ†ãƒ³ãƒ—ãƒ¬ãƒ¼ãƒˆ
template: |
        <${arxiv_url}|*${title_trans}*>
        ğŸ‘¤ *Authors*: ${authors}
        ğŸ”‘ *Keywords*: ${words}
        âš½ *Score*: ${score}
        ğŸ“ *Abstract*:
        ã€€${summary_trans}
        ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£ï¿£
